version: "3.3"
services:
  mongodb:
    image: mongo:3.5
    volumes:
      - type: bind
        source: ./data/db
        target: /data/db
  web:
    image: tenlee/yapi:1.6.1
    links:
      - mongodb:mongodb
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./config.json
        target: /yapi/config.json
      - type: bind
        source: ./data/yapi
        target: /home/yapi/log
