version: "3.3"
services:
  mongodb:
    image: mongo:3.5
    volumes:
      - type: bind
        source: ./data/db
        target: /data/db
  web:
    image: tenlee/yapi:1.6.2
    #command: /bin/bash -c "[ ! -e /home/yapi/log/init.lock ] && npm run install-server && touch /home/yapi/log/init.lock; npm run start"
    entrypoint: /yapi/entrypoint.sh
    links:
      - mongodb:mongodb
    ports:
      - 3000:3000
    tty: true
    volumes:
      - type: bind
        source: ./config.json
        target: /yapi/config.json
      - type: bind
        source: ./data/yapi
        target: /yapi/log
      - type: bind
        source: ./entrypoint.sh
        target: /yapi/entrypoint.sh
